/*
 * ssd1306_i2c.c
 *
 * Driver for I2C version of ssd1306 driver.
 */
#include "sdkconfig.h" // generated by "make menuconfig"

#if CONFIG_SSD1306_I2C_ENABLED

#include <string.h>
#include <sys/types.h>

#include "freertos/FreeRTOS.h"
#include "freertos/timers.h"

#include "driver/gpio.h"
#include "driver/i2c.h"
#include "esp_err.h"
#include "esp_log.h"


#include "display.h"
#include "ssd1306_i2c_internal.h"
#include "font.h"

#include "font8x8_basic.h"

#define TAG "SSD1306"

#define SSD1306_EXTERNAL_VCC  true

static void ssd1306_i2c_reset(display_t *display)
{
    display->_lock(display);

    ssd1306_i2c_driver_info* driver_info = (ssd1306_i2c_driver_info*) (display->driver_info);

ESP_LOGI(TAG, "%s: reset_pin %d", __func__, driver_info->reset_pin);

    gpio_set_level(driver_info->reset_pin, 0);
    vTaskDelay(pdMS_TO_TICKS(20));
    gpio_set_level(driver_info->reset_pin, 1);
    vTaskDelay(pdMS_TO_TICKS(10));

    display->_unlock(display);
}


static void i2c_master_init(display_t* display, int i2c_num, int sda_pin, int scl_pin, int reset_pin, int clk_speed)
{
    ssd1306_i2c_driver_info* driver_info = (ssd1306_i2c_driver_info*) (display->driver_info);

ESP_LOGI(TAG, "%s: i2c_num %d  sda_pin %d  scl_pin %d  reset_pin %d  clk_speed %d", __func__, i2c_num, sda_pin, scl_pin, reset_pin, clk_speed);

    i2c_config_t i2c_config = {
        .mode = I2C_MODE_MASTER,
        .sda_io_num = sda_pin,
        .sda_pullup_en = GPIO_PULLUP_ENABLE,
        .scl_io_num = scl_pin,
        .scl_pullup_en = GPIO_PULLUP_ENABLE,
        .master.clk_speed = clk_speed,
    };

    ESP_ERROR_CHECK(i2c_param_config(i2c_num, &i2c_config));

    ESP_ERROR_CHECK(i2c_driver_install(i2c_num, I2C_MODE_MASTER, 0, 0, 0));

    driver_info->i2c_num = i2c_num;

    gpio_config_t io = {
        .intr_type = GPIO_PIN_INTR_DISABLE,
        .mode = GPIO_MODE_OUTPUT,
        .pin_bit_mask = 1ULL << reset_pin,
        .pull_down_en = 0,
        .pull_up_en = GPIO_PULLUP_ENABLE,
    };

    ESP_ERROR_CHECK(gpio_config(&io));

    driver_info->reset_pin = reset_pin;

    ssd1306_i2c_reset(display);
}

void ssd1306_i2c_init(display_t* display)
{
    display->_lock(display);

    ssd1306_i2c_driver_info* driver_info = (ssd1306_i2c_driver_info*) (display->driver_info);

    i2c_cmd_handle_t cmd = i2c_cmd_link_create();

    ESP_ERROR_CHECK(i2c_master_start(cmd));

    ESP_ERROR_CHECK(i2c_master_write_byte(cmd, (CONFIG_SSD1306_I2C_ADDR << 1) | I2C_MASTER_WRITE, true));
    ESP_ERROR_CHECK(i2c_master_write_byte(cmd, SSD1306_CONTROL_BYTE_CMD_STREAM, true));

    ESP_ERROR_CHECK(i2c_master_write_byte(cmd, SSD1306_CMD_DISPLAY_OFF, true));

    ESP_ERROR_CHECK(i2c_master_write_byte(cmd, SSD1306_CMD_SET_MUX_RATIO, true));
    ESP_ERROR_CHECK(i2c_master_write_byte(cmd, display->height - 1, true));

    ESP_ERROR_CHECK(i2c_master_write_byte(cmd, SSD1306_CMD_SET_DISPLAY_OFFSET, true));
    ESP_ERROR_CHECK(i2c_master_write_byte(cmd, 0x00, true));

    ESP_ERROR_CHECK(i2c_master_write_byte(cmd, SSD1306_CMD_SET_DISPLAY_START_LINE | 0x00, true));

    ESP_ERROR_CHECK(i2c_master_write_byte(cmd, display->flags & DISPLAY_FLAGS_MIRROR_X ? SSD1306_CMD_SET_SEGMENT_NORMAL : SSD1306_CMD_SET_SEGMENT_REMAP, true));
    ESP_ERROR_CHECK(i2c_master_write_byte(cmd, display->flags & DISPLAY_FLAGS_MIRROR_Y ? SSD1306_CMD_SET_COM_SCAN_NORMAL : SSD1306_CMD_SET_COM_SCAN_REMAP, true));

    ESP_ERROR_CHECK(i2c_master_write_byte(cmd, SSD1306_CMD_SET_COM_PIN_MAP, true));
    ESP_ERROR_CHECK(i2c_master_write_byte(cmd, display->height == 32 ? 0x10 : 0x12, true)); // 0x10 if 32 lines else 0x12

    /* Initial brightness as 0 so old stuff doesn't get displayed */
    ESP_ERROR_CHECK(i2c_master_write_byte(cmd, SSD1306_CMD_SET_CONTRAST, true));
    ESP_ERROR_CHECK(i2c_master_write_byte(cmd, 0, true));

    ESP_ERROR_CHECK(i2c_master_write_byte(cmd, SSD1306_CMD_DISPLAY_RAM, true));

    ESP_ERROR_CHECK(i2c_master_write_byte(cmd, SSD1306_CMD_DISPLAY_NORMAL, true));

    ESP_ERROR_CHECK(i2c_master_write_byte(cmd, SSD1306_CMD_SET_DISPLAY_CLK_DIV, true));
    ESP_ERROR_CHECK(i2c_master_write_byte(cmd, 0x80, true));  // 0x80?

    ESP_ERROR_CHECK(i2c_master_write_byte(cmd, SSD1306_CMD_SET_CHARGE_PUMP, true));
    ESP_ERROR_CHECK(i2c_master_write_byte(cmd, SSD1306_EXTERNAL_VCC ? 0x14 : 0x10, true));

    ESP_ERROR_CHECK(i2c_master_write_byte(cmd, SSD1306_CMD_DISPLAY_ON, true));


    ESP_ERROR_CHECK(i2c_master_write_byte(cmd, SSD1306_CMD_SET_MEMORY_ADDR_MODE, true));
    ESP_ERROR_CHECK(i2c_master_write_byte(cmd, SSD1306_PARAM_MEMORY_ADDR_MODE_HORIZONTAL, true));

    ESP_ERROR_CHECK(i2c_master_write_byte(cmd, SSD1306_CMD_SET_PRECHARGE, true));
    ESP_ERROR_CHECK(i2c_master_write_byte(cmd, 0x22, true));

    ESP_ERROR_CHECK(i2c_master_write_byte(cmd, SSD1306_CMD_SET_VCOMH_DESELECT, true));
    ESP_ERROR_CHECK(i2c_master_write_byte(cmd, 0x30, true));

    ESP_ERROR_CHECK(i2c_master_stop(cmd));

ESP_LOGI(TAG, "%s: i2c_num %d cmd %p port tick period %d", __func__, driver_info->i2c_num, cmd, portTICK_PERIOD_MS);

    ESP_ERROR_CHECK(i2c_master_cmd_begin(driver_info->i2c_num, cmd, 1000/portTICK_PERIOD_MS));
//    esp_error_t espRc = i2c_master_cmd_begin(driver_info->i2c_num, cmd, 10/portTICK_PERIOD_MS);
//
//    if (espRc == ESP_OK) {
//        ESP_LOGI(TAG, "%s: OLED configured successfully", __func__);
//    } else {
//        ESP_LOGE(TAG, "%s: OLED configuration failed. code: 0x%.2X", __func__, espRc);
//    }

    i2c_cmd_link_delete(cmd);

    display->_unlock(display);
}

static void ssd1306_i2c_deinit(display_t* display)
{
    /* Clear the display */
    display->clear(display);

    /* Disconnect i2c */
    display->enable(display, false);
}

static void ssd1306_i2c_enable(display_t* display, bool enable)
{
    display->_lock(display);

    ssd1306_i2c_driver_info* driver_info = (ssd1306_i2c_driver_info*) (display->driver_info);

    i2c_cmd_handle_t cmd = i2c_cmd_link_create();

    i2c_master_start(cmd);
    i2c_master_write_byte(cmd, (CONFIG_SSD1306_I2C_ADDR << 1) | I2C_MASTER_WRITE, true);
    i2c_master_write_byte(cmd, SSD1306_CONTROL_BYTE_CMD_SINGLE, true);
    i2c_master_write_byte(cmd, enable ? SSD1306_CMD_DISPLAY_ON : SSD1306_CMD_DISPLAY_OFF, true);
    i2c_master_stop(cmd);

    i2c_master_cmd_begin(driver_info->i2c_num, cmd, 10/portTICK_PERIOD_MS);
    i2c_cmd_link_delete(cmd);

    display->_unlock(display);
}

static void ssd1306_i2c_contrast(display_t* display, int contrast)
{
    display->_lock(display);

    ssd1306_i2c_driver_info* driver_info = (ssd1306_i2c_driver_info*) (display->driver_info);

    i2c_cmd_handle_t cmd = i2c_cmd_link_create();
    i2c_master_start(cmd);
    i2c_master_write_byte(cmd, (CONFIG_SSD1306_I2C_ADDR << 1) | I2C_MASTER_WRITE, true);
    i2c_master_write_byte(cmd, SSD1306_CONTROL_BYTE_CMD_STREAM, true);
    i2c_master_write_byte(cmd, SSD1306_CMD_SET_CONTRAST, true);
    i2c_master_write_byte(cmd, contrast, true);

    i2c_master_stop(cmd);
    i2c_master_cmd_begin(driver_info->i2c_num, cmd, 10/portTICK_PERIOD_MS);
    i2c_cmd_link_delete(cmd);

    display->_unlock(display);
}

/*
 * Write current frame buffer to device.
 */
static void ssd1306_i2c_show(display_t* display)
{
    display->_lock(display);

    ssd1306_i2c_driver_info* driver_info = (ssd1306_i2c_driver_info*) (display->driver_info);

    i2c_cmd_handle_t cmd = i2c_cmd_link_create();

ESP_LOGI(TAG, "%s: cmd %p,  %d bytes", __func__, cmd, display->frame_len);

    ESP_ERROR_CHECK(i2c_master_start(cmd));
    ESP_ERROR_CHECK(i2c_master_write_byte(cmd, (CONFIG_SSD1306_I2C_ADDR << 1) | I2C_MASTER_WRITE, true));
    ESP_ERROR_CHECK(i2c_master_write_byte(cmd, SSD1306_CONTROL_BYTE_DATA_STREAM, true));
    ESP_ERROR_CHECK(i2c_master_write(cmd, display->frame_buf, display->frame_len, true));
    ESP_ERROR_CHECK(i2c_master_stop(cmd));

    ESP_ERROR_CHECK(i2c_master_cmd_begin(driver_info->i2c_num, cmd, 10/portTICK_PERIOD_MS));

    i2c_cmd_link_delete(cmd);

    display->_unlock(display);
}

/*
 * Close the device and free structures
 */
static void ssd1306_i2c_close(display_t* display)
{
    display->_lock(display);

    ssd1306_i2c_driver_info* driver_info = (ssd1306_i2c_driver_info*) (display->driver_info);

    ssd1306_i2c_deinit(display);

    display->_unlock(display);

    free((void*) display->driver_info);

    /* Call the close routine in the parent class (frees the class) */
    driver_info->close(display);

    /* Free our local storage */
    free((void*) driver_info);

}

/*
 * If caller knows what they are doing, construct one from whole cloth.
 */
display_t *ssd1306_i2c_create_raw(int i2c_num, int sda_pin, int scl_pin, int reset_pin, int clk_speed, int width, int height, uint8_t flags)
{
    display_t *display = display_create(width, height, flags);

    if (display != NULL) {

ESP_LOGI(TAG, "%s: i2c_num %d sda_pin %d scl_pin %d reset_pin %d clk_speed %d width %d height %d", __func__, i2c_num, sda_pin, scl_pin, reset_pin, clk_speed, width, height);

        ssd1306_i2c_driver_info *driver_info = (ssd1306_i2c_driver_info*) malloc(sizeof(ssd1306_i2c_driver_info));

        display->driver_info = (void*) driver_info;

        /* Assign a default font */
        display->set_font(display, &font8x8_basic);

        ESP_LOGI(TAG, "%s: initializing i2c num %d sda %d scl %d reset %d speed %d", __func__, i2c_num, sda_pin, scl_pin, reset_pin, clk_speed);
        i2c_master_init(display, i2c_num, sda_pin, scl_pin, reset_pin, clk_speed);

        ESP_LOGI(TAG, "%s: initializing display", __func__);
        ssd1306_i2c_init(display);

        /* Plug override for close */
        driver_info->close     = display->close;

        display->_show         = ssd1306_i2c_show;

        display->close         = ssd1306_i2c_close;

        display->contrast      = ssd1306_i2c_contrast;
        display->enable        = ssd1306_i2c_enable;

        /* Clear the display */
        display->clear(display);

        display->contrast(display, 0x80);

    }

    ESP_LOGI(TAG, "%s: returning %p", __func__, display);
    return display;
}

display_t *ssd1306_i2c_create(uint8_t flags)
{
    return ssd1306_i2c_create_raw(
                  CONFIG_SSD1306_I2C_CHANNEL_NUMBER,
                  CONFIG_SSD1306_I2C_SDA_GPIO,
                  CONFIG_SSD1306_I2C_SCL_GPIO,
                  CONFIG_SSD1306_I2C_RESET_GPIO,
                  CONFIG_SSD1306_I2C_CLK_SPEED,
                  CONFIG_SSD1306_I2C_WIDTH,
                  CONFIG_SSD1306_I2C_HEIGHT,
                  flags
           );
}

#endif /* CONFIG_SSD1306_I2C_ENABLED */
